swipe:
  3: 
    left: 
      command: 'xdotool key alt+Right'
    right: 
      command: 'xdotool key alt+Left'
    up: 
      command: 'xdotool key super+Up'
    down: 
      command: 'xdotool key super+Down'
  4:
    down: 
      command: 'xdotool key super+s'
    up: 
      command: 'xdotool key super+s'

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
